name: Deploy Front-end

on:
  workflow_dispatch: # add run button in github

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x, 12.x, 14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Deploy
      run: |
        npm run deploy
